name: Build Docker image
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-20.04
    name: Build with Docker
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
